name: best-rq

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pytorch=1.11.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3
  - numpy==1.23.5
  - pre-commit=3.2.2
  - faiss-gpu==1.7.3
  - pip:
      - -r requirements.txt
