name: best-rq

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch==2.0.0
  - torchaudio==2.0.0
  - pytorch-cuda=11.8
  - numpy==1.23.5
  - pre-commit=3.2.2
  - faiss-gpu==1.7.4
  - pip:
      - -r requirements.txt
